### ISSUE TITLE
append option does not work in latest Chrome browser.

### ISSUE THREAD

**Issue by Annuther** [DoersGuild/jQuery.print#101]
### Windows 8.1 running (Latest) Chrome Version 69.0.3497.100 (Official Build) (32-bit)

The **append** option does not work - even on your own demo it fails to print the supplied content :
`<br/>Buh Bye!`

Any chance of a fix??

**Comment by sathvikp** [comment]
Looks like a change in behavior in jQuery for strings starting with a `<br/>`, wrapped in a span and it works as expected. Thank you for bringing it up
