### ISSUE TITLE
Number of copies

### ISSUE THREAD

**Issue by justwooper** [DoersGuild/jQuery.print#104]
Hi, is there a way I can send the number of copies? I need it because I use this plugin to send barcodes to zebra printer and it always prints 1, is there a way? thanks

**Comment by sathvikp** [comment]
That is not possible on most browsers by default (along with a lot of other print options), mainly as a security measure.
One way is you could [clone the element](https://stackoverflow.com/questions/12835582/how-to-clone-a-element-n-times) manually the required number of times and call print on the jQuery object
Another would be to use modified browsers like Chrome on the Kiosk mode or IE with ActiveX

**Comment by justwooper** [comment]
Thanks for the reply, I will try to clone the element and call the print function, I think that it would work, thanks
