### ISSUE TITLE
How to make this plugin printing more than one page?

### ISSUE THREAD

**Issue by firmlab** [DoersGuild/jQuery.print#106]
Hello, I'm stuck on printing long HTML, which is need more than one page.
How i can do that? I tried to print long HTML, but the result it's get cut.

**Comment by sathvikp** [comment]
It should print it just fine as long as there's no css restricting the page height - please create a sample simplified jsFiddle showcasing this issue for us to help you better
Thanks!




---- On Tue, 08 Oct 2019 21:50:22 +0530 notifications@github.com wrote ----



Hello, I'm stuck on printing long HTML, which is need more than one page.
How i can do that? I tried to print long HTML, but the result it's get cut.

**Comment by firmlab** [comment]
Hi, thanks for the reply,

the print html is like this: https://jsfiddle.net/8e0yun6k/ but in here it's working fine.

i think you're right, the problem is because of there is css that restrict it's height.

i'm using framework7 popup and i put the HTML print template into it.

have you ever use framework7 before?
how to make this template override the restriction?

**Comment by sathvikp** [comment]
No, perhaps try posting on StackOverflow?
You may need to use the browser console inspector to identify the erring css and override it in the print css




---- On Tue, 08 Oct 2019 22:15:27 +0530 notifications@github.com wrote ----



Hi, thanks for the reply,

the print html is like this: https://jsfiddle.net/8e0yun6k/ but in here it's working fine.

i think you're right, the problem is because of there is css that restrict it's height.

i'm using framework7 popup and i put the HTML print template into it.

have you ever use framework7 before?
how to make this template override the restriction?

**Comment by firmlab** [comment]
ah, i fixed it with _globalStyles_ to false.

but is there any way to setup margin on each of print?
let say, i have 2 print template, one for **receipt print** and one for **standard print**, is there any option to set the margin only for **standard print** ?

**Comment by sathvikp** [comment]
Use print css - or append/prepend appropriate css margins




---- On Tue, 08 Oct 2019 22:34:31 +0530 notifications@github.com wrote ----



ah, i fixed it with globalStyles to false.

but is there any way to setup margin on each of print?
let say, i have 2 print template, one for receipt print and one for standard print, is there any option to set the margin only for standard print ?

**Comment by firmlab** [comment]
like this one?

<style id="custom-style-print">
@page { 
  margin: 0cm 0cm 0cm 0cm; 
}
</style>

$('#print-registrasi-container').print({append: '#custom-style-print'});

**Comment by sathvikp** [comment]
Sure, that could work but you may be better off using one of these options:

#### mediaPrint

 - Default: `false`  
 - Acceptable-Values: Boolean  
 - Function: Whether or not link tags with media='print' should be included; Over-riden by the `globalStyles` option

#### stylesheet

 - Default: `null`
 - Acceptable-Values: URL-string
 - Function: URL of an external stylesheet to be included
