### ISSUE TITLE
Please enable adding of multiple css files and larger screens.

### ISSUE THREAD

**Issue by Mashiane** [DoersGuild/jQuery.print#107]
### Expected behaviour
Grid printout with 6x2 columns on larger screens printed properly.

### Observed behaviour
Grid printout with 6x2 columns on larger screens is printed as 12x2 on the print preview.
![6x2](https://user-images.githubusercontent.com/5799306/67051781-5fda8900-f13c-11e9-95e0-2e6cd3d50509.png)

### Steps to reproduce the issue

![12x2](https://user-images.githubusercontent.com/5799306/67051947-fb6bf980-f13c-11e9-80f2-34dae0b6b224.png)

### jQuery, jQuery.print version
Latest
### Browser and operating system
Chrome/Opera

Also, can you please enable adding multiple stylesheet files and not just 1.

Thanks

**Comment by CitizenOfRome** [comment]
For anyone else running into this:
Reg the grid thing - that's the browser default CSS print behaviour, the grid continues to be responsive even while printing
You could work around this by setting a `min-width` on the grid via the print css
