### ISSUE TITLE
Rename filename when save as pdf

### ISSUE THREAD

**Issue by rassemdev** [DoersGuild/jQuery.print#111]
When i choose save as pdf, the filename comes up with  some name default name. Is there any way i can customize the filename!

**Comment by juliyvchirkov** [comment]
> When i choose save as pdf, the filename comes up with some name default name. Is there any way i can customize the filename!

Just print with separate window instead of iframe and set your own title. A browser will use the title as filename for PDF

``` javascript
    jQuery('#elementToPrint').print({
        iframe : false,
        title : 'My Own Customized PDF name'
    })
