### ISSUE TITLE
Checked checkboxes where printed as unchecked

### ISSUE THREAD

**Issue by crebuh** [DoersGuild/jQuery.print#14]
Hi!
I got a weird problem. I cannot print checked checkboxes. For example we got a list of bookings and there is a checkbox in each row to show if the booking has been paid or not.

When I try to print the list, none of the checkboxes are checked in the preview of the printer.
Does anybody know, why this is happening?

thx!

**Comment by sathvikp** [comment]
The latest version (v1.3.0) should address this as well, see #11 
Please let us know if it doesn't. Thanks!
