### ISSUE TITLE
Pagination possible?

### ISSUE THREAD

**Issue by visioncode** [DoersGuild/jQuery.print#15]
First of alle - thanks for your work! It is a simple but nice plugin. 

Do you think it is possibe to get a pagination done with it? I would like to auto-append "Page X of Y" at every new page.

Any ideas?

**Comment by sathvikp** [comment]
Sure, just use the `append` option, like

```js
$("#myElementId").print({
    append: "Page X of Y"
});
```
it'll print with "Page X of Y" appended at the end of #myElementId

**Comment by pelodelfuego** [comment]
How about append page numbers on each page? 
Is it possible?

**Comment by sathvikp** [comment]
Yes, you could use [CSS counters](http://stackoverflow.com/a/20317775/937891) to do that
