### ISSUE TITLE
console error jquery not defined

### ISSUE THREAD

**Issue by coldes** [DoersGuild/jQuery.print#16]
First of all - love what you done, has solved a problem I had with printing all content in a modal window  - however kept getting Console error using
```javascript
<button class="print-link" onclick="jquery.print('#sectiontoprint')">PRINT</button>
```
(index):368 Uncaught ReferenceError: jquery is not defined
My solution is
```javascript
    <button a href="javascript:void(0);" class="print-link">PRINT</button>
```
All works plus no Console error
When checking your demo it is console error free 

Curious as to why I was getting the ReferenceError: jquery is not defined?

**Comment by sathvikp** [comment]
The 'Q' must be capitalized - it's 'jQuery'

**Comment by coldes** [comment]
..always the little thing - thank you

fyi - forgot to mention previously - the file jQuery.print.js is not included in the ZIP file from github

**Comment by sathvikp** [comment]
That's strange, both https://github.com/DoersGuild/jQuery.print/archive/master.zip and https://github.com/DoersGuild/jQuery.print/archive/1.3.1.zip have jQuery.print.js when I download them. 
Which link are you using?

**Comment by coldes** [comment]
...my apologies - I went straight into the demo folder - thank you for
responding anyway
