### ISSUE TITLE
Won't get changed form values from textareas...

### ISSUE THREAD

**Issue by ssuess** [DoersGuild/jQuery.print#18]
Hi, I have included this code on my page and it will print what is on the page wonderfully, with one exception: I have a couple of textareas on the page that I need to put text into and have that print with the page, but the values will not get printed. Whatever values those textareas hold at page load (one of them has default values) WILL print, but if I make any changes to the content of those textareas, those will NOT print, only the original copy will. I have checked that manuallyCopyFormValues is set to true, but no luck. Any ideas?

**Comment by ssuess** [comment]
Well, I have a workaround, but it isn't pretty. By using jquery to force set the text (not val) of the textarea after entering text but before printing, the print code will now pick it up.

**Comment by sathvikp** [comment]
Thanks, fixed!
`manuallyCopyFormValues` basically does the same thing, I had somehow missed adding support for textareas when I wrote it earlier

Please take a look and let me know if there are any issues still

**Comment by ssuess** [comment]
Thanks!

**Comment by ssuess** [comment]
actually, the new code doesn't work for me, I reverted back to my fix, which was essentially a separate function on the page that sets the values onblur:

   `jQuery(function() {
    jQuery("textarea.fromto").blur(function () {
    if(jQuery(this).val()!= ""  ) {
     jQuery("textarea.fromto").text(jQuery(this).val());
    } 
    }
    });`

**Comment by sathvikp** [comment]
Hmm, that's odd, because that is essentially what we're doing [here](https://github.com/DoersGuild/jQuery.print/blob/1a5fae505e4bc72438f46c0865a3bcc1782be04e/jQuery.print.js#L150), only right before we insert the selected content into an iframe for printing rather than on-blur:

```js
copy.find("textarea").each(function () {
   // Fix for https://github.com/DoersGuild/jQuery.print/issues/18#issuecomment-96451589
  var $field = $(this);
  $field.text($field.val());
});
```

**Comment by ssuess** [comment]
I don't understand either, it looks very similar. Let me go back through the code and see if anything sticks out...

**Comment by ssuess** [comment]
I don't understand why you closed the other bug in relation to this one, they seem quite separate issues to me.

**Comment by KevinNBaer** [comment]
This added to the jQuery.print.js object will get the textareas cloned correctly.

    (function (original) {
      jQuery.fn.clone = function () {
        var result = original.apply (this, arguments),
            my_textareas = this.find('textarea'),
            result_textareas = result.find('textarea'),
            my_selects = this.find('select'),
            result_selects = result.find('select');

        for (var i = 0, l = my_textareas.length; i < l; ++i)
          $(result_textareas[i]).val ($(my_textareas[i]).val());

        for (var i = 0, l = my_selects.length; i < l; ++i)
          $(result_selects[i]).val ($(my_selects[i]).val());

        return result;
      };
    }) (jQuery.fn.clone);
