### ISSUE TITLE
Show Url in Printing

### ISSUE THREAD

**Issue by athenaneo** [DoersGuild/jQuery.print#20]
Sir,

Using jQuery.print.js When printing a table including link [ one colomn as <a href="..." type]  , In printing time the corresponding url is displayed on printing page. 
I Want to avoid That Url.please help me

**Comment by sathvikp** [comment]
Not sure I follow, could you please setup a demo somewhere, perhaps on jsfiddle?

Thanks!

**Comment by athenaneo** [comment]
<table width="200" border="1" id="MyTable">
  <tr>
    <th scope="row">no</th>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <th scope="row">1</th>
    <td><a href="aa.php">View</a></td>
  </tr>
  <tr>
    <th scope="row">2</th>
    <td><a href="ab.php">Edit</a></td>
  </tr>
  
</table>


url aa.php and ab.php that is shown in colomn of table during the printing time.
I want to avoid that url during the printing time.
that is the problem

**Comment by sathvikp** [comment]
I'm still not sure I understand what you're saying @athenaneo
Do you mean to hide a certain column/cells while printing your table?

**Comment by kabelo38** [comment]
I think his referring to the text printed on the text on the top right side of the page

**Comment by sathvikp** [comment]
@kabelo38 Apparently the print header and footer (containing the page URL) are a [browser-client preference that we can't control](http://stackoverflow.com/a/2192840/937891), though there is a [workaround that may work on some browsers](http://stackoverflow.com/a/2780518/937891)
