### ISSUE TITLE
scroll Issue

### ISSUE THREAD

**Issue by Muneem** [DoersGuild/jQuery.print#21]
I have table which have scroll. If i print that table then it doesnot handle scroll

**Comment by sathvikp** [comment]
Could you please setup a demo on jsfiddle or a similar site so that I can
help you better.
Thanks

**Comment by kabelo38** [comment]
me 2 i have a table that has Showing 1 to 756 of 756 entries but when i print i only get 18 entries

**Comment by derekmcclure** [comment]
Here is an example:  https://jsfiddle.net/w406083x/26/

**Comment by sathvikp** [comment]
@derekmcclure Thanks for the example. In this case if you're referring to the right half of the table not being displayed, it is a CSS issue, try running it with [`globalStyles: false`](https://jsfiddle.net/w406083x/28/) and append new styles to make it fit better.

@kabelo38 Some plugins only load a certain set of rows into the DOM tree especially when rendering large tables, `jQuery.print` can only print what's already loaded

**Comment by derekmcclure** [comment]
My issue is the rows are all loaded on the grid, but they don't render in the printout.

I'm ok with the columns running off the page.

On Aug 1, 2015, at 9:13 AM, Sathvik Ponangi <notifications@github.com<mailto:notifications@github.com>> wrote:


@derekmcclure<https://github.com/derekmcclure> Thanks for the example. In this case if you're referring to the right half of the table not being displayed, it is a CSS issue, try running it with globalStyles: false<https://jsfiddle.net/w406083x/28/> and append new styles to make it fit better.

@kabelo38<https://github.com/kabelo38> Some plugins only load a certain set of rows into the DOM tree especially when rendering large tables, jQuery.print can only print what's already loaded

**Comment by sathvikp** [comment]
@derekmcclure Please take a look at https://jsfiddle.net/w406083x/28/, it's the same code with `globalStyles` set to `false` - as you can see it shows all the rows from "Benedetti_7B" to "Edmisten_6C" (tested on Chrome 44 on Win7x64), you just need to adjust the CSS to make it more presentable and show all the data

**Comment by derekmcclure** [comment]
Wonderful, thank you!
