### ISSUE TITLE
How to avoid extra blank page at end while printing?

### ISSUE THREAD

**Issue by Francks11** [DoersGuild/jQuery.print#25]
If I add this css : 

```
<style>
@media print {
    html, body {
        height: 99%;    
    }
}
</style>
```

Its works, but is there a cleaner way?

Thanks

**Comment by sathvikp** [comment]
The extra page showing up is usually purely determined by your content, and going by this StackOverflow Question - https://stackoverflow.com/questions/7846346/how-to-avoid-extra-blank-page-at-end-while-printing, there doesn't seems to be any other generic way to fix this, perhaps you could try asking a follow up question there?
