### ISSUE TITLE
not printing <input> tags and artefacts with iCheck plugin

### ISSUE THREAD

**Issue by boomsya** [DoersGuild/jQuery.print#28]
hi
i am using your plugin. best of all
but today i found what my <input type='text'> not printing

and when i use plugin
https://github.com/fronteed/iCheck/
then radio-boxes prints with artefacts

**Comment by sathvikp** [comment]
Could you please create a demo JSFiddle so that I can better understand your issue?
Thanks!

**Comment by boomsya** [comment]
ok. i will send for you screenshot at Monday
