### ISSUE TITLE
How to use the page break with the plugin

### ISSUE THREAD

**Issue by rodrigosarri** [DoersGuild/jQuery.print#30]
I'm trying to use a CSS to make a page break. Follows suit:

HTML:

`<a href="#" class="print">print</a>`
`<div id="print">`
    `<div id="first">`
     content
   `</div>`
   `<div id="second">`
     content
   `</div>`
`</div>`

CSS: 

@media print {
    #first{
      page-break-after: always;
   }
}

I also tried
@media print {
    #second{
      page-break-before: always;
   }
}

js 

$(document).on('click','.print', function() {
   $('#print').print();
});

Can you help me? Please.

Thank you

**Comment by sathvikp** [comment]
Sorry I couldn't write back earlier.
Could you please put this in a JSFIddle so that I can better understand the issue and tweak your case?
Thanks!

**Comment by sirio3mil** [comment]
page-break doesn't work. 

Question is easy, how insert page break?, I have two images on a div, i want to print each image on a different page, there is a way?

Regards

**Comment by Mashuk-EIS** [comment]
Can I break down page without using canvas. Just html content ? My div is long enough to display in a page.
