### ISSUE TITLE
it does not work with Zurb foundation reveal

### ISSUE THREAD

**Issue by ssoulless** [DoersGuild/jQuery.print#31]
how to use this plugin to print the contents of a Zurb Foundation reveal modal?

**Comment by sathvikp** [comment]
The plugin should be able to print any element that's in the browser's DOM
Could you please create an example jsFiddle demonstrating the issue?
Thanks!

On 24 November 2015 at 08:32, Sebastian Velandia <notifications@github.com>
wrote:

> how to use this plugin to print the contents of a Zurb Foundation reveal
> modal?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DoersGuild/jQuery.print/issues/31>.
>



-- 
Sathvik
Doers' Guild <http://www.doersguild.com>
RWD Doers Guild Internet Solutions Pvt. Ltd.
