### ISSUE TITLE
hello, rendering problem with class of boostrap.. 

### ISSUE THREAD

**Issue by fabirus** [DoersGuild/jQuery.print#34]

**Comment by fabirus** [comment]
demo here http://jsfiddle.net/fabirus/nfupbv3v/

**Comment by sathvikp** [comment]
Printing of colors, etc is typically a user setting
You can try with [`-webkit-print-color-adjust: exact;`](https://jsfiddle.net/nfupbv3v/1/), but the support isn't guaranteed across all browsers - more info: http://stackoverflow.com/q/14987496/937891

**Comment by fabirus** [comment]
thanks, this method is working in google chrome but don't working in firefox, the css is not applying

**Comment by sathvikp** [comment]
See http://stackoverflow.com/a/15253634/937891

**Comment by sathvikp** [comment]
And: http://stackoverflow.com/a/22632508/937891
