### ISSUE TITLE
Not Working on ie 

### ISSUE THREAD

**Issue by aykutbasan** [DoersGuild/jQuery.print#35]
![image](https://cloud.githubusercontent.com/assets/15124942/11806751/e0077f14-a31d-11e5-8f70-9d4469e2d90c.png)

**Comment by sathvikp** [comment]
I'm not quite sure I understand your issue, could you please create a demo on some site like JSFiddle so that I can better understand what's not working on IE and why. Thanks!

**Comment by aykutbasan** [comment]
Hi, 
Thank you for fast replay. May be its my local browser fault. My test case is 
1. Demo page http://doersguild.github.io/jQuery.print/demo/, 
2. Click any print this button.
3. An error appeared. 

Browser version is IE 11.0.9600.18125

Thanks

**Comment by aykutbasan** [comment]
Sory its about un stable ie version. Thank you.
