### ISSUE TITLE
IE9 not printing border-radius, alpha transparent background-color, and semi-transparent SVG paths

### ISSUE THREAD

**Issue by nothingisnecessary** [DoersGuild/jQuery.print#36]
Thank you for great plugin - smart idea to inject content into iframe and print that.

Noticed some problems with Internet Explorer 9 not printing SVG paths and marker clusters with `backgroundcolor: rgba()` and not handling border-radius correctly (while printing Leaflet.js maps using Leaflet-easy-print https://github.com/rowanwins/leaflet-easyPrint). I believe this is because IE9 requires HTML5 doctype to print these things.

Easy fix was to write the DOCTYPE before the content:

                wdoc.open();
                wdoc.write("<!DOCTYPE html>");
                wdoc.write(content);

Considering pull request, but I dunno if IE9 support is big deal for you or not. Thoughts?

**Comment by sathvikp** [comment]
Thanks, a new `doctype` option has been added!
