### ISSUE TITLE
Orientation

### ISSUE THREAD

**Issue by jdenijs** [DoersGuild/jQuery.print#39]
Dear sir,

I have implemented your print solution succesfully, great piece of work!

I would like to make a suggestion to add an option to set the orientation of the print to landscape or portrait.

Kind regards,

Jos de Nijs

**Comment by sathvikp** [comment]
Glad you found it useful!
Please have a look at http://stackoverflow.com/a/1392794/937891, a CSS solution that you could load via @media print.

Thanks!
