### ISSUE TITLE
Plugin randomly failing in Iframe mode

### ISSUE THREAD

**Issue by SethMusulin** [DoersGuild/jQuery.print#40]
Hey guys, thank you for putting the plugin together.  I have noticed both in development and in your own example page that when in iframe mode, the print screen will randomly be blank when printing.  I was unable to track down what might be causing this.  I am on Mac, El Capitan, Chrome v 48.0.2564.116.

**Comment by sesubash** [comment]
Facing the same issue. Any fix for it?

**Comment by sesubash** [comment]
This pull request fixes this issue I think [#52](https://github.com/DoersGuild/jQuery.print/pull/52)

**Comment by sathvikp** [comment]
Could you kindly check with the latest version v1.5.0 and let me know if the issue persists?
Thanks!

**Comment by SethMusulin** [comment]
@sathvikp , sorry I ended up having to use another tool because of some tight timelines so I am not able to confirm that this has been fixed.

**Comment by sathvikp** [comment]
Thanks for the update, no worries
