### ISSUE TITLE
No print dialog

### ISSUE THREAD

**Issue by oojacoboo** [DoersGuild/jQuery.print#45]
So, I've setup things and it's working fine outside of iframe mode.  However, in iframe mode, while it does add the iframe to the DOM, it doesn't trigger the print dialog.  Any ideas?

I should mention that I'm using FF48.0a2

**Comment by oojacoboo** [comment]
Closing my own issue 8 min later :)

The issue was related to the timeout.  It'd be great if the docs were updated a bit to make that value a bit more clear.  Thanks for the great work on this lib!

**Comment by sathvikp** [comment]
> while it does add the iframe to the DOM, it doesn't trigger the print dialog

Did it print a blank page or was it that nothing at all happened?

**Comment by oojacoboo** [comment]
Nothing happened, no dialog box ever appeared.

**Comment by sathvikp** [comment]
Could you kindly check with the latest version v1.5.0 and let me know if the issue persists?
Thanks!
