### ISSUE TITLE
new window - not tab

### ISSUE THREAD

**Issue by oojacoboo** [DoersGuild/jQuery.print#46]
It'd be a great addition to have the non-iframe mode open a new window and not a new tab.  Also, setting the width/height of that window would be great.

**Comment by sathvikp** [comment]
The new tab is set to auto-close after printing - are you looking for something like a print preview?

**Comment by oojacoboo** [comment]
Right, it would be for a print preview.  It would also trigger the print dialog, or optionally so.  I didn't realize the tab closed after printing - maybe I didn't test it far enough to see that happen.  I probably hit cancel, but the tab didn't disappear.

**Comment by sathvikp** [comment]
The new tab seems to auto close as expected when tested in multiple environments - let me know if it doesn't auto-close with any particular browser/version

As for the print-preview feature, I'm not looking to implement it myself at the moment, but would be happy to accept PRs
