### ISSUE TITLE
Blowing up after about 10 pages in IE11

### ISSUE THREAD

**Issue by GregTVan** [DoersGuild/jQuery.print#47]
We are printing approx. 30 printed pages of HTML as PDF. It looks good until page 10, when we see the below and nothing else prints. On Chrome, with all the same code, it prints fine. FF also has a similar issue but sooner, at 3 pages. This is from Windows 7, jQuery 1.11, jQuery print 1.3.3. Any thoughts?

ERROR: invalidaccess
OFFENDING COMMAND: put
STACK:
/116
1
[/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef
/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef
/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef
/.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef /.notdef
/space /exclam /quotedbl /numbersign /dollar /percent /ampersand /
quoteright /parenleft /parenright /asterisk

**Comment by GregTVan** [comment]
ps: I tried it with jQuery Print 1.4, same result.

**Comment by sathvikp** [comment]
Could you try and see if increasing the `timeout` option helps?
I suspect the print is being triggered before the entire element is fully loaded.

**Comment by GregTVan** [comment]
tried that but will try again. thanks very much for the reply.

**Comment by sathvikp** [comment]
Also it would be quite helpful if you could create a simplified demo on
jsFiddle or a similar site to help you debug better.

On 10 June 2016 at 10:55, GregTVan <notifications@github.com> wrote:

> tried that but will try again. thanks very much for the reply.
>
> On Thursday, 9 June 2016, Sathvik Ponangi <notifications@github.com>
> wrote:
>
> > Could you try and see if increasing the timeout option helps?
> > I suspect the print is being triggered before the entire element is fully
> > loaded.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/DoersGuild/jQuery.print/issues/47#issuecomment-225095959
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ABHAalOCbdRUpgZ40lXv4mv83HIxP4bxks5qKPT8gaJpZM4Iya0O
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/DoersGuild/jQuery.print/issues/47#issuecomment-225096095>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA2sk_pZGVMLzPIYfqcFjlZKRq73KedQks5qKPVUgaJpZM4Iya0O>
> .
>



-- 
Sathvik
Doers' Guild
<http://t.sidekickopen54.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LqWkjW6443-21q0T7nW3Ljg7x56dK-rf8GfzwT02?t=http%3A%2F%2Fwww.doersguild.com%2F&si=5680052904132608&pi=75a69613-02f1-47e2-d930-b6f68983889d>
RWD Doers Guild Internet Solutions Pvt. Ltd.

**Comment by GregTVan** [comment]
Excellent suggestion, thank you again.

**Comment by GregTVan** [comment]
Hi sathvikp. It turns out, from our point of view, I believe there is no problem with jQuery print. If we print the identical file using jQuery print, it blows up with CutePDF, but it works fine with browser print preview and a physical printer. So I believe the issue is with CutePDF. It's something to do with not recognizing some of the fonts loaded with @font-face. Curiously, it only occurs with IE and FF; Chrome is fine (isn't that always the way), even with CutePDF. Anyway, I am closing this issue here. Thanks again for your reply, cheers, Greg
