### ISSUE TITLE
Print beyond one page?

### ISSUE THREAD

**Issue by campwise** [DoersGuild/jQuery.print#48]
Am using default options except I bumped timeout to 950. Printing in Chrome or IE 11 never goes past first page of the iFrame, the scrollbars are visible in print preview and also print but not any content beyond page 1. Any suggestions? Thanks.

**Comment by sathvikp** [comment]
That's quite weird, do you think you could quickly create a demo JSFiddle
of the same?

Thanks!

On 10 June 2016 at 22:23, campwise <notifications@github.com> wrote:

> Am using default options except I bumped timeout to 950. Printing in Crome
> or IE never goes past first page of the iFrame, the scrollbars are visible
> in print preview and also print but not any content beyond page 1. Any
> suggestions? Thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DoersGuild/jQuery.print/issues/48>, or mute the thread
> <https://github.com/notifications/unsubscribe/AA2sk2F9iO2lkS0O37wmcfvpFc6806b2ks5qKZZ1gaJpZM4IzIdt>
> .
>



-- 
Sathvik
Doers' Guild
<http://t.sidekickopen54.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LqWkjW6443-21q0T7nW3Ljg7x56dK-rf8GfzwT02?t=http%3A%2F%2Fwww.doersguild.com%2F&si=5680052904132608&pi=1d3e6291-2387-47c6-8ad4-b505a0dfb7c1>
RWD Doers Guild Internet Solutions Pvt. Ltd.

**Comment by campwise** [comment]
Could it be because my content resides in an iFrame, which has a scroll bar?

**Comment by sathvikp** [comment]
Yeah, that could be it.
You can directly print the iframe's content, this plugin does just that by
putting the selected element's content in an iframe and printing it.

**Comment by campwise** [comment]
I have fixed this issue. Thanks.
