### ISSUE TITLE
Print is not working in ipad

### ISSUE THREAD

**Issue by sesubash** [DoersGuild/jQuery.print#56]
Print is not working in iPad. It goes blank if try to print. Attached the screenshot.

![ipad_print](https://cloud.githubusercontent.com/assets/4628269/18988661/56a2de70-8725-11e6-992f-9aa1d3a7dc54.jpg)

**Comment by sathvikp** [comment]
The demo on the gh-pages branch was using an older version of jQuery.print, kindly check if it's any better now.

Another issue on iOS and Android is that triggering print on a hidden iframe (that this plugin uses to print the selected content) causes the whole parent page to be printed instead. I'm not sure if it works as expected with the `iframe: false` option. If it does, could you kindly let me know so that we can document this workaround?

Thanks!

**Comment by abhi001** [comment]
@sesubash @sathvikp 

I was working on this plugin and fixed this issue for printing on iPad in the demo application.
To fix this issue, we have to make these two changes in code-

There an issue with focus on iframe in iOS while **frameWindow.document.execCommand('print', false, null)** , so i have added a hidden div at absolute position to keep focus on current window not iframe

Add this code

```
else{
	$('<div id="print-alert">Print called successfully !</div>').appendTo('body').css({"position": "absolute","top": -999,"left": -999});
}
```

After adding the above code, It will be like -

![image](https://cloud.githubusercontent.com/assets/4137391/20420942/d88d5eba-ad86-11e6-9d90-f3012f0d8ef1.png)

 After closing print iframe either printing successfully or cancelling the print command, remove added content from your html document  - 

```
if( document.getElementById("print-alert") ){
	$(document.getElementById("print-alert")).remove();
}
```

Modify setTimeout timestamp to  1000 ms

**`}, 1000);`**

![image](https://cloud.githubusercontent.com/assets/4137391/20420825/20c45860-ad86-11e6-9c8f-0a4e3f0c3117.png)

Output -

![img_0075](https://cloud.githubusercontent.com/assets/4137391/20421106/ee8f9aa6-ad87-11e6-8ac7-81a7950f56b2.PNG)

**Comment by sesubash** [comment]
@abhi001 Thanks for your hint. Since losing focus on body is the issue, I have added focus to body to fix this issue instead of adding an element and removing it on the fly. Verified the updated code in iPad and it works like charm. @sathvikp I updated the code and raised PR.

**Comment by molfar** [comment]
You fix (fork) works in iphone, but not in ipad...

**Comment by sesubash** [comment]
@molfar This fix works well in iPad Air 2.

**Comment by molfar** [comment]
Does not work in iPad air. Android also not working. But in iPhone 5s works ok. Here is demo https://youtu.be/OTTtrxvDAGo

**Comment by sesubash** [comment]
@molfar I checked in real device it works. Also I noticed print preview itself not triggered for you in browser stack. Check it in real device please.

**Comment by molfar** [comment]
@sesubash We checked in real device, ipad with ios9 - not working, iphone with ios10 - works. android - does not work at all.

**Comment by sesubash** [comment]
@molfar Please find the screenshot took from iPad Air 2. 
![img_0385](https://cloud.githubusercontent.com/assets/4628269/20746385/7ee58118-b69a-11e6-9912-2fd622e96e00.PNG)

**Comment by molfar** [comment]
@sesubash I'm really confused. You show it in ipad air 2, but what version of ios do you have there?

**Comment by sesubash** [comment]
@molfar iPad Air, OS version 10.1.1

**Comment by molfar** [comment]
@sesubash But it does not work in iOS9, also on ipad air 2. May be there is some os specific issue? Also it is reported that script does not work in android devices at all.

**Comment by sesubash** [comment]
@molfar Just checked in Android device and it seems to be working. Attached the screenshot.
![andriod_jquery print](https://cloud.githubusercontent.com/assets/4628269/20751110/160df6e4-b720-11e6-8c6b-514664d033a9.jpeg)

But I don't have iOS9 to check with.

**Comment by sathvikp** [comment]
Kindly confirm that the latest version v1.5.1 fixes this
Thanks!

**Comment by guncebektas** [comment]
it seems it always try to print whole page in android (tested with chrome) and it's working in iphone7 (tested with safari)

**Comment by rajkishoreworks** [comment]
Not working at all with android(6,7) chrome. It prints the whole page instead just iframe.

**Comment by sathvikp** [comment]
This is a [known bug with older versions of Chrome on Android](https://bugs.chromium.org/p/chromium/issues/detail?id=561438) - it should work normally with iFrames as of Chrome 61
