### ISSUE TITLE
How to print in landscape mode by default.

### ISSUE THREAD

**Issue by neeraj24a** [DoersGuild/jQuery.print#57]
I have to print a page content who has bigger content in width want to print it in landscape mode by default but i am not able to find any option to print in landscape mode by default.

**Comment by sathvikp** [comment]
Please take a look at http://stackoverflow.com/a/1392794/937891
```css
@media print{@page {size: landscape}}
```
```html
<style type="text/css" media="print">
    .page
    {
     -webkit-transform: rotate(-90deg); 
     -moz-transform:rotate(-90deg);
     filter:progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
    }
</style>
```
