### ISSUE TITLE
How to use the deferred option to remove something after printing

### ISSUE THREAD

**Issue by igsoap** [DoersGuild/jQuery.print#60]
Hi 

I am still learning javascript and jquery. I couldnt quite understand how to use deferred. So I am hoping the author can give me some pointer.

I made a function to append the information I want to print at the bottom of the page. then it triggers the printing process, and I want to remove the appened <div> after the print window is shown. 

my code look something like the code below. 

$("#appendlisthere").on('click','.printme',function(){
            var content =  "some content for append";
            $("#printme").append(content);
            $("#printme").print({
                deferred: ,
            });
    });

what should I put in deferred option so I can $("#printme").empty(). so the newly appened content is deleted.

**Comment by sathvikp** [comment]
```js
$("#appendlisthere").on('click','.printme',function(){
    var content = "some content for append";
    $("#printme").append(content);
    $("#printme").print({
        deferred: $.Deferred().done(function() {
            $("#printme").empty();
        }),
    });
});
```
See: https://api.jquery.com/deferred.done/ and https://learn.jquery.com/code-organization/deferreds/examples/

Although in this particular case you're likely better off not putting the content in the DOM at all and directly printing it instead, as this plugin [`clone`s](https://api.jquery.com/clone/) the selected element and inserts it in an iframe/new window for printing:
```js
$("#appendlisthere").on('click','.printme',function(){
    var content = "some content for append";
    $('<span/>').append(content).print();
});
```
