### ISSUE TITLE
how reload page after click on print button

### ISSUE THREAD

**Issue by bcaspar** [DoersGuild/jQuery.print#62]
Hi,

How can I  reload my page after click on print button?
Thank you.

Brice

**Comment by sathvikp** [comment]
I'm not sure why you'd want to do that, but you can use the `deferred` option - see https://github.com/DoersGuild/jQuery.print/wiki/Using-the-deferred-option-to-set-up-a-callback-after-printing

```js
jQuery(function($) {
    'use strict';
    $('#myElement').print({
        deferred: $.Deferred().done(function() {
            window.location.reload();
        })
    });
});
```

**Comment by bcaspar** [comment]
Thank you, it's perfect.

Brice

Le lun. 5 déc. 2016 à 13:59, Sathvik Ponangi <notifications@github.com> a
écrit :
