### ISSUE TITLE
jQuery.print page refresh/load issue with Edge Browser

### ISSUE THREAD

**Issue by khari512** [DoersGuild/jQuery.print#63]
Hi,

When we try to print a part of the page with jQuery.print plugin, for very first time its refreshing or reloading the page in IE Edge browser.

Thanks,
Harinath

**Comment by sathvikp** [comment]
I can't seem to replicate this on Microsoft Edge 38.14393.0.0, Windows 10 with http://doersguild.github.io/jQuery.print/demo/
Could you kindly [create](https://jsfiddle.net)/share a demo page showing this issue?
