### ISSUE TITLE
打印内容超过一页。

### ISSUE THREAD

**Issue by menglyf** [DoersGuild/jQuery.print#74]
我的打印内容在一个table里面，如果内容过长。并且ie，firefox，chrome的打印效果不一样。请问怎么处理

**Comment by sathvikp** [comment]
没有保证的解决方案，您将不得不使用您的CSS，以使其在浏览器中或多或少一致。 请参阅：http://stackoverflow.com/a/3697543/937891

另一种选择当然是使用服务器生成的PDF文件，无论他们使用什么浏览器，都应该始终打印。

There is no guaranteed solution for this, you will have to play around with your CSS to make it more or less consistent across browsers. See: http://stackoverflow.com/a/3697543/937891

An alternative is of-course use a server generated PDF file which should print consistently no matter what browser they use.
