### ISSUE TITLE
Printing Blank Pages if the print request has more than 2 pages in Chrome Kiosk Printing mode

### ISSUE THREAD

**Issue by akreddy21** [DoersGuild/jQuery.print#77]
We have a requirement to print the messages automatically whenever they were pulled and saved in our system and for that we are using the Chrome browser in the kiosk printing mode(--kiosk-printing). Problem is when we have more than 2 messages to print , First 2 messages were printing properly and remaining all  were printing as blank papers. 
I tried [https://github.com/DoersGuild/jQuery.print/issues/43](url) some of the suggestion you provided in that bug, but none of them worked out. 
If i am printing normally i mean with print preview everything was working fine. 
Any thoughts why only 2 messages are printing properly ? remaining all are blank in Kiosk Printing Mode?

**Comment by sathvikp** [comment]
Were you able to fix it?
This sounds a lot like an old Chrome bug - https://bugs.chromium.org/p/chromium/issues/detail?id=136343 - maybe it popped up again? 
As its working fine in the regular mode, I'd try uninstalling chrome and installing an older, hopefully more stable version
