### ISSUE TITLE
Saving file to server instead of opening print window

### ISSUE THREAD

**Issue by cob1** [DoersGuild/jQuery.print#86]
Hi! The plugin works as a charm. I'm trying to get it working to save the generated .PDF as a file on server. My guess is that I have to do it with an AJAX call but I don't know how to pick the raw data of the generated PDF in a variable and pass it to a PHP function that does the saving. Could anyone kindly give me a hand on this ? I'm using jQuery.print.js version 1.5.1.

**Comment by sathvikp** [comment]
The most direct way to do this would be to skip the plugin and pick up the HTML yourself via `$myEl.html()` and post that to your server for saving.
The plugin does have a [`deferred.notify`](https://api.jquery.com/deferred.notify/) event once the content has been prepared for printing and you can access the same through a [`deferred.progress`](https://api.jquery.com/deferred.progress/) callback on the `deferred` option in the plugin similar to https://github.com/DoersGuild/jQuery.print/wiki/Using-the-deferred-option-to-set-up-a-callback-after-printing
```js
    $('#myElement').print({
        deferred: $.Deferred().progress(function(event, content, $cloneElement) {
            if(event === 'generated_markup') {
                // Send 'content' to server - it contains the HTML string which is put into an iframe/window for printing
                $.post('/my-endpoint', { content: content });
            }
        })
    });
```
