### ISSUE TITLE
CSS path problem after packaging

### ISSUE THREAD

**Issue by wzc570738205** [DoersGuild/jQuery.print#88]
### Expected behaviour
 * The path is correct
### Observed behaviour
 * The path is reported to 404 under the server
### Steps to reproduce the issue
![_20180321161057](https://user-images.githubusercontent.com/21350874/37699449-8f1b93b0-2d22-11e8-82f4-81405cb251e4.png)
![_20180321161113](https://user-images.githubusercontent.com/21350874/37699454-93fd279a-2d22-11e8-99f0-eef111ce67b2.png)
### jQuery, jQuery.print version
 * jQuery v2.1.4 

 * jQuery.print, version 1.5.1

### Browser and operating system
 * chrome 
 * window

Hello, trouble me to look at this path
I can run it locally, but this path will be wrong after packing

**Comment by sathvikp** [comment]
Kindly ensure that the relative path you are using is correct after packaging
The issue seems to be specific to your setup, if you can create a simplified demo on JSFiddle or a similar site, I or someone else may be able to take a look at it and help you out
