### ISSUE TITLE
No Print Selector

### ISSUE THREAD

**Issue by tmblog** [DoersGuild/jQuery.print#89]
I am assuming that adding the the `class="avoid-this"` will not print anything in there?

I have a table with few rows each with a unique ID and within that row I also have a print button, so it'll print the button be default I know, I am trying to exclude the button but so far unable to.

`<input class="print-link avoid-this" type="submit" value="Print" onclick="jQuery('#<?php echo $row->id;?>').print()">`

How do I exclude those that I don't need? So far adding the avoid-this class isn't working, because the IDs are auto generated, is it possible to pass the no selector class in the above example?

The print version is 1.5.1 and using jquery 3.1.0, on Firefox 59.0.1 windows 10.
Any help would be much appreciated.

**Comment by sathvikp** [comment]
You have to pass the selector for the elements you want to skip using the [`noPrintSelector` option](https://github.com/DoersGuild/jQuery.print#noprintselector), like `noPrintSelector: ".avoid-this"`

**Comment by sathvikp** [comment]
`<input class="print-link avoid-this" type="submit" value="Print" onclick="jQuery('#<?php echo $row->id;?>').print({noPrintSelector: ".avoid-this"})">`
