### ISSUE TITLE
The Table is shown as Vertical table instead of Horizontal table in Printing Preview

### ISSUE THREAD

**Issue by trungkienit08** [DoersGuild/jQuery.print#91]
### Browser and operating system

Hi,

We have encountered an issue. When in Printing Preview mode (in Chrome), our table is shown as the Vertical table instead of the Horizontal table, we are expecting it to be shown as the Horizontal table, and our table has total 14 columns, we still couldn't find a way to resolve this, please help to give an advice. 

Thank you.

**Comment by sathvikp** [comment]
You will have to tweak around your print CSS to try and make your table look the way you need it to be.
I or someone else may be able to guide you further if share screenshots and a jsfiddle demo showcasing your issue. You could also try posting the same on StackOverflow.com to get further help
