### ISSUE TITLE
how to know print is success or print is fail?

### ISSUE THREAD

**Issue by chelsh** [DoersGuild/jQuery.print#92]
how to know print is success or print is fail?

**Comment by sathvikp** [comment]
There seems to be no cross browser way to surely know this, but you could try https://stackoverflow.com/a/18325463/937891
You can also use the deferred option promise which resolves based on whether errors occurred during the plugin's activity - https://github.com/DoersGuild/jQuery.print/wiki/Using-the-deferred-option-to-set-up-a-callback-after-printing
