### ISSUE TITLE
Suggestion for append and prepend

### ISSUE THREAD

**Issue by saidbakr** [DoersGuild/jQuery.print#95]
### Expected behaviour
Append/Prepend should accept array of elements instead of just one element.
### Observed behaviour
Currently it accepts one element.
### Steps to reproduce the issue
N/A
### Simplified demo link reproducing the issue
N/A
### jQuery, jQuery.print version
N/A, 1.5.1
### Browser and operating system
N/A

**Comment by saidbakr** [comment]
I just noticed that, supplying comma separated values to the append property of elements, leads to appending them successfully to the printer. i.e:

```
$("#ele").print({
append: '#anE1,#anE2'
});
```
**However**, the order appended elements keeps their respective order in the DOM, regarding less any change of their order in the append string, i.e. '#anE2,#anE1` is the same order as `#anE1,#anE2`

**Comment by sathvikp** [comment]
It accepts any valid jQuery selector or object (and internally performs `$(options.append).clone()`)
If you need to retain a custom order, you could build a new temporary jQuery object like:
```
var $append = $('<span/>');
$append.append($('#anE2').clone());
$append.append($('#anE1').clone());
$('#ele').print({
    append: $append
});
```
