### ISSUE TITLE
unable to reload page when print pop up is opened

### ISSUE THREAD

**Issue by sanals** [DoersGuild/jQuery.print#96]
### Expected behaviour
Reload page when print pop up is open

### Observed behaviour
Can't Reload page when print pop up is open

### Steps to reproduce the issue
What prevents current page say 'page_1' from reloading when jQuery.print pops up in 'page_1'? The same reason prevents me from reloading the parent page say 'page_0', since i am loading 'page_1' from 'page_0' with window.open('page_1'). I am unable to do any  task in the parent(page_0) page when the print window is opened within the child(page_1) page.

### Simplified demo link reproducing the issue
none

### jQuery, jQuery.print version
jquery-2.1.1, jQuery.print - 1.3.3

### Browser and operating system
chrome 64.0.3282.167 64-bit, ubuntu 16.04

**Comment by sathvikp** [comment]
I'm not sure I fully grasp the issue, a simplified demo on jsfiddle.net or similar may help me help you
Based on what I understood, please see if the following help:
- https://productforums.google.com/forum/#!topic/chrome/nPu_myJ0xEA
- https://stackoverflow.com/questions/14462163/google-chrome-blocks-ajax-requests-when-print-preview-is-opened-on-child-window
- https://bugs.chromium.org/p/chromium/issues/detail?id=146516
