### ISSUE TITLE
Two instances of printer popup loading

### ISSUE THREAD

**Issue by drkrtj** [DoersGuild/jQuery.print#98]

**Comment by drkrtj** [comment]
Hello,
    I am sure I am doing something wrong. I am getting two instances of the printer popup showing which triggers the, "Prevent this page from creating additional dialogs". How do I correct this issue? Here is my button and script setup. 
 Thanks



<button class="giftcert_check_mo_mailprint_button" id="print_giftcert_check_mo_mailform" onclick="jQuery.print()">Printout Form</button>



<script>
		jQuery(function($) { 
			'use strict';
            
            $(".payment_processing_check_by_mail").find('#print_giftcert_check_mo_mailform').on('click', function() {
                //Print with custom options
				
                $(".giftcert_checkmailform").print( {
					globalStyles: true,
					mediaPrint: true,
					stylesheet: null,
					noPrintSelector: ".no-print",
					iframe: true,
					append: null,
					prepend: null,
					manuallyCopyFormValues: true,
					deferred: $.Deferred(),
					timeout: 750,
					title: null,
					doctype: '<!doctype html>'
				});
            });
		});
</script>

**Comment by drkrtj** [comment]
<button class="giftcert_check_mo_mailprint_button" id="print_giftcert_check_mo_mailform" onclick="jQuery.print()">Printout Form</button>

**Comment by drkrtj** [comment]
`<button class="giftcert_check_mo_mailprint_button" id="print_giftcert_check_mo_mailform" onclick="jQuery.print()">Printout Form</button>`


`<script>
		jQuery(function($) { 
			'use strict';
            
            $(".payment_processing_check_by_mail").find('#print_giftcert_check_mo_mailform').on('click', function() {
                //Print with custom options
				
                $(".giftcert_checkmailform").print( {
					globalStyles: true,
					mediaPrint: true,
					stylesheet: null,
					noPrintSelector: ".no-print",
					iframe: true,
					append: null,
					prepend: null,
					manuallyCopyFormValues: true,
					deferred: $.Deferred(),
					timeout: 750,
					title: null,
					doctype: '<!doctype html>'
				});
            });
		});
</script>`

**Comment by sathvikp** [comment]
You are calling it twice, once in the HTML onclick and then the script tag

**Comment by drkrtj** [comment]
Hello Sathvik, thanks a lot. I appreciate your help. One more question. I am having difficulty figuring out how to get a select/options value to show up in the print. Can you help me to achieve this?

       Thanks,
                Kenny



--------------------------------------------
On Sun, 8/19/18, Sathvik Ponangi <notifications@github.com> wrote:

 Subject: Re: [DoersGuild/jQuery.print] Two instances of printer popup loading (#98)
 To: "DoersGuild/jQuery.print" <jQuery.print@noreply.github.com>
 Cc: "drkrtj" <drkrtj@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Sunday, August 19, 2018, 4:03 PM
 
 You are calling it twice, once in
 the HTML onclick and then the script tag
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
