### ISSUE TITLE
user selected (select/options) value not showing up in the print

### ISSUE THREAD

**Issue by drkrtj** [DoersGuild/jQuery.print#99]

**Comment by drkrtj** [comment]
Hello Sathvik, thanks a lot. I appreciate your help. One more question. I am having difficulty figuring out how to get the selected (select/options) value from the dropdown list to show up in the print. The jQuery.print.js only prints the default starting value regardless of what the user selects. The default value is, "select your country". If the user selects India it will show on the screen but the printed version will revert back to, "select your country".

**Comment by sathvikp** [comment]
Could you kindly create a simple jsFiddle demo showing the issue?

Thank you

**Comment by sathvikp** [comment]
Kindly try with the latest v1.6.0 and let me know

**Comment by drkrtj** [comment]
Hello Sathvik, thanks for the reply. I have never put anything on jsfiddle but here is my best shot. Select one of the countries then print it out. You should see that the country you selected will disappear from your printed version.

https://jsfiddle.net/hgtsc085/22/


--------------------------------------------
On Mon, 8/20/18, Sathvik Ponangi <notifications@github.com> wrote:

 Subject: Re: [DoersGuild/jQuery.print] user selected (select/options) value not showing up in the print (#99)
 To: "DoersGuild/jQuery.print" <jQuery.print@noreply.github.com>
 Cc: "drkrtj" <drkrtj@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Monday, August 20, 2018, 8:36 PM
 
 Could you kindly create a simple
 jsFiddle demo showing the issue?
 Thank you
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by drkrtj** [comment]
Hello Sathvik, thanks sooooo very much. You are definitely the man!!! I think we are in business now. 


--------------------------------------------
On Mon, 8/20/18, Sathvik Ponangi <notifications@github.com> wrote:

 Subject: Re: [DoersGuild/jQuery.print] user selected (select/options) value not showing up in the print (#99)
 To: "DoersGuild/jQuery.print" <jQuery.print@noreply.github.com>
 Cc: "drkrtj" <drkrtj@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Monday, August 20, 2018, 9:13 PM
 
 Kindly try with the latest v1.6.0
 and let me know
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by sathvikp** [comment]
👍
P.S. You can use the Resources section in the laft-side-panel on jsFiddle to import jQuery.print (or other libraries) instead of pasting the code directly

**Comment by drkrtj** [comment]
Thanks a lot. That is good to know.

--------------------------------------------
On Tue, 8/21/18, Sathvik Ponangi <notifications@github.com> wrote:

 Subject: Re: [DoersGuild/jQuery.print] user selected (select/options) value not showing up in the print (#99)
 To: "DoersGuild/jQuery.print" <jQuery.print@noreply.github.com>
 Cc: "drkrtj" <drkrtj@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Tuesday, August 21, 2018, 12:50 AM
 
 👍
 
 P.S. You can use the Resources section in the
 laft-side-panel on jsFiddle to import jQuery.print (or other
 libraries) instead of pasting the code directly
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
